version: 2

builds:
  - builder: zig
    flags:
      - -Doptimize=ReleaseFast
    targets:
      - x86_64-linux
      - x86_64-windows
      - aarch64-linux
      - x86_64-macos
      - aarch64-macos

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]

brews:
  - repository:
      owner: waynezhang
      name: homebrew-tap
    commit_author:
      name: waynezhang
      email: linghua.zhang@me.com
    homepage: "https://github.com/waynezhang/toyskkserv"
    description: "A toy SKK skkseev. Just made this for fun."
    license: "MIT License"
    skip_upload: auto
    service: |
      run [opt_bin/"toyskkserv", "serve"]
      keep_alive true
      log_path var/"log/toyskkserv.log"
      error_log_path var/"log/toyskkserv.log"
